import type { Metadata, Viewport } from "next";
import { ViewTransitions } from "next-view-transitions";
import { displayFont, bodyFont } from "@/lib/fonts";
import { site } from "@content/site";
import { organisationJsonLd } from "@/lib/seo";
import SmoothScroll from "@/components/layout/SmoothScroll";
import Preloader from "@/components/layout/Preloader";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} - Architecture, Interior & Engineering`,
    template: `%s - ${site.name}`,
  },
  description: site.description,
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    siteName: site.name,
    title: site.name,
    description: site.description,
    locale: "en_IN",
    url: "/",
    // Generated by scripts/build-brand-assets.mjs. Project pages override this
    // with their own hero. Without it, every share previews as a blank card -
    // which matters, since the practice distributes almost entirely over
    // Instagram and WhatsApp.
    images: [
      {
        url: "/media/og/default.jpg",
        width: 1200,
        height: 630,
        alt: `${site.name} - ${site.tagline}`,
      },
    ],
  },
  twitter: { card: "summary_large_image" },
  robots: { index: true, follow: true },
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  themeColor: "#1a2333", // matches --color-ink
  colorScheme: "light",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ViewTransitions>
      <html lang="en" className={`${displayFont.variable} ${bodyFont.variable}`}>
        <head>
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(organisationJsonLd()) }}
          />
        </head>
        <body>
          <noscript>
            {/* The reveal primitives start hidden and are faded in by GSAP.
                Without JS that would leave the page blank. */}
            <style>
              {"[data-reveal]{opacity:1 !important}[data-preloader]{display:none !important}"}
            </style>
          </noscript>
          <a
            href="#main"
            className="label focus:bg-ink focus:text-bone sr-only focus:not-sr-only focus:fixed focus:top-6 focus:left-6 focus:z-[200] focus:px-4 focus:py-3"
          >
            Skip to content
          </a>
          <Preloader />
          <SmoothScroll />
          <Header />
          <main id="main">{children}</main>
          <Footer />
        </body>
      </html>
    </ViewTransitions>
  );
}
