import type { Metadata, Viewport } from "next";
import { ViewTransitions } from "next-view-transitions";
import { displayFont, bodyFont } from "@/lib/fonts";
import { getSite } from "@/lib/content";
import SiteProvider from "@/components/layout/SiteProvider";
import "./globals.css";

export async function generateMetadata(): Promise<Metadata> {
  const site = await getSite();
  return {
    metadataBase: new URL(site.url),
    title: {
      default: `${site.name} - Architecture, Interior & Engineering`,
      template: `%s - ${site.name}`,
    },
    description: site.description,
    alternates: { canonical: "/" },
    openGraph: {
      type: "website",
      siteName: site.name,
      title: site.name,
      description: site.description,
      locale: "en_IN",
      url: "/",
      // Generated by scripts/build-brand-assets.mjs. Project pages override this
      // with their own image. Without it, every share previews as a blank card -
      // which matters, since the practice distributes almost entirely over
      // Instagram and WhatsApp.
      images: [
        {
          url: "/media/og/default.jpg",
          width: 1200,
          height: 630,
          alt: `${site.name} - ${site.tagline}`,
        },
      ],
    },
    twitter: { card: "summary_large_image" },
    robots: { index: true, follow: true },
    manifest: "/manifest.webmanifest",
  };
}

export const viewport: Viewport = {
  themeColor: "#1a2333", // matches --color-ink
  colorScheme: "light",
};

/**
 * Just the document. The public site's header, footer and scrolling live in
 * app/(site)/layout.tsx, so /admin can have a plain layout of its own.
 */
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const site = await getSite();
  return (
    <ViewTransitions>
      <html lang="en" className={`${displayFont.variable} ${bodyFont.variable}`}>
        <body>
          <noscript>
            {/* The reveal primitives start hidden and are faded in by GSAP.
                Without JS that would leave the page blank. */}
            <style>
              {"[data-reveal]{opacity:1 !important}[data-preloader]{display:none !important}"}
            </style>
          </noscript>
          <SiteProvider site={site}>{children}</SiteProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
